<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="David Noble – 668 454 671" />

<meta name="date" content="2025-11-30" />

<title>Open Data Network Business Intelligence Report</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">David Noble Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="projects.html">Projects</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Open Data Network Business Intelligence
Report</h1>
<h3 class="subtitle">Data-Driven Management Analysis</h3>
<h4 class="author">David Noble – 668 454 671</h4>
<h4 class="date">2025-11-30</h4>

</div>

<div id="TOC">
<ul>
<li><a href="#question-1---business-problem-definition"
id="toc-question-1---business-problem-definition">Question 1 - Business
Problem Definition</a>
<ul>
<li><a href="#problem-statement" id="toc-problem-statement">Problem
Statement</a></li>
</ul></li>
<li><a href="#question-2---data-source-assessment"
id="toc-question-2---data-source-assessment">Question 2 - Data Source
Assessment</a>
<ul>
<li><a href="#q2.-a" id="toc-q2.-a">Q2. A</a></li>
<li><a href="#q2.-b" id="toc-q2.-b">Q2. B</a></li>
<li><a href="#q2.-c" id="toc-q2.-c">Q2. C</a></li>
</ul></li>
<li><a href="#question-3---data-analysis"
id="toc-question-3---data-analysis">Question 3 - Data Analysis</a>
<ul>
<li><a href="#q3.-a" id="toc-q3.-a">Q3. A</a></li>
<li><a href="#q3.-b" id="toc-q3.-b">Q3. B</a></li>
<li><a href="#q3.-c" id="toc-q3.-c">Q3. C</a></li>
</ul></li>
<li><a href="#question-4---strategic-recommendations"
id="toc-question-4---strategic-recommendations">Question 4 - Strategic
Recommendations</a>
<ul>
<li><a href="#q4.-a" id="toc-q4.-a">Q4. A</a></li>
</ul></li>
</ul>
</div>

<pre class="r"><code>library(ggplot2)
library(scales)
library(dplyr)
library(tibble)
library(knitr)
wine_quality &lt;- read.csv(&quot;data/wine_quality.csv&quot;)</code></pre>
<p><br> <br></p>
<div id="question-1---business-problem-definition"
class="section level2">
<h2>Question 1 - Business Problem Definition</h2>
<p><br></p>
<div id="problem-statement" class="section level3">
<h3>Problem Statement</h3>
<blockquote>
<p>Noble Wines by Latulippe, a bourgie wine start‑up, needs to identify
which production variables influence wine quality in order to optimize
its fermentation process without inflating costs. By analyzing chemical
properties data from red wine samples, we can pinpoint the key
production markers that drive quality and shape the production of our
flagship wine.</p>
</blockquote>
<p><br></p>
<hr />
</div>
</div>
<div id="question-2---data-source-assessment" class="section level2">
<h2>Question 2 - Data Source Assessment</h2>
<p><br></p>
<div id="q2.-a" class="section level3">
<h3>Q2. A</h3>
<blockquote>
<p>Our wine quality dataset originates from the Instituto Superior de
Engenharia do Porto (ISEP) in Portugal. It contains measurements and
quality ratings of Portuguese red wines collected between 2004 and 2007.
The dataset was originally created for scientific research in oenology.
Each observation represents a lab‑analyzed wine sample, with 11
measurable variables and one subjective taste‑tester rating. The study
is complete and no longer updated, reflecting data from a specific time
period and region. Known limitations include the subjectivity of quality
scores from taste‑testers and the geographic restriction to a single
region.</p>
</blockquote>
<p><br></p>
</div>
<div id="q2.-b" class="section level3">
<h3>Q2. B</h3>
<blockquote>
<p>Our dataset for this project was accessed on the Kaggle webpage: <a
href="https://www.kaggle.com/datasets/uciml/red-wine-quality-cortez-et-al-2009">Wine
Quality Dataset</a>. We downloaded the wine_quality.csv file and loaded
it into the RStudio environment using:</p>
<pre><code>wine_quality &lt;- read.csv(&quot;data/wine_quality.csv&quot;)  </code></pre>
<p>This allows our .Rmd document to run independently without relying on
external data sources or an internet connection.</p>
</blockquote>
<p><br></p>
</div>
<div id="q2.-c" class="section level3">
<h3>Q2. C</h3>
<blockquote>
<p>The wine quality dataset contains 1,599 observations and 12
variables, with no missing values. Its numeric variables are well‑suited
for quantitative analysis, and categorical groupings can be derived
directly from quality scores (e.g., acidity levels grouped from low-3 to
high-8). No imputation or data cleaning was required. The source is
credible, originating from ISEP and published through the University of
California Irvine’s Machine Learning Repository, a resource widely cited
in both academic and industry research.</p>
<p><br></p>
<p>This dataset directly supports business decisions aimed at product
quality improvement. Noble Wines by Latulippe can analyze how
physicochemical properties — such as acidity, additives and alcohol
content — influence consumer ratings to refine production processes. By
linking measurable chemical attributes to perceived quality,
recommendations can be made that guide strategic decisions in the wine
market.</p>
</blockquote>
<pre class="r"><code># examine data
dim(wine_quality)</code></pre>
<pre><code>## [1] 1599   12</code></pre>
<pre class="r"><code>str(wine_quality) </code></pre>
<pre><code>## &#39;data.frame&#39;:    1599 obs. of  12 variables:
##  $ fixed.acidity       : num  7.4 7.8 7.8 11.2 7.4 7.4 7.9 7.3 7.8 7.5 ...
##  $ volatile.acidity    : num  0.7 0.88 0.76 0.28 0.7 0.66 0.6 0.65 0.58 0.5 ...
##  $ citric.acid         : num  0 0 0.04 0.56 0 0 0.06 0 0.02 0.36 ...
##  $ residual.sugar      : num  1.9 2.6 2.3 1.9 1.9 1.8 1.6 1.2 2 6.1 ...
##  $ chlorides           : num  0.076 0.098 0.092 0.075 0.076 0.075 0.069 0.065 0.073 0.071 ...
##  $ free.sulfur.dioxide : num  11 25 15 17 11 13 15 15 9 17 ...
##  $ total.sulfur.dioxide: num  34 67 54 60 34 40 59 21 18 102 ...
##  $ density             : num  0.998 0.997 0.997 0.998 0.998 ...
##  $ pH                  : num  3.51 3.2 3.26 3.16 3.51 3.51 3.3 3.39 3.36 3.35 ...
##  $ sulphates           : num  0.56 0.68 0.65 0.58 0.56 0.56 0.46 0.47 0.57 0.8 ...
##  $ alcohol             : num  9.4 9.8 9.8 9.8 9.4 9.4 9.4 10 9.5 10.5 ...
##  $ quality             : int  5 5 5 6 5 5 5 7 7 5 ...</code></pre>
<pre class="r"><code># data completeness check
colSums(is.na(wine_quality))</code></pre>
<pre><code>##        fixed.acidity     volatile.acidity          citric.acid 
##                    0                    0                    0 
##       residual.sugar            chlorides  free.sulfur.dioxide 
##                    0                    0                    0 
## total.sulfur.dioxide              density                   pH 
##                    0                    0                    0 
##            sulphates              alcohol              quality 
##                    0                    0                    0</code></pre>
<pre class="r"><code>(colSums(is.na(wine_quality)) / nrow(wine_quality)) * 100</code></pre>
<pre><code>##        fixed.acidity     volatile.acidity          citric.acid 
##                    0                    0                    0 
##       residual.sugar            chlorides  free.sulfur.dioxide 
##                    0                    0                    0 
## total.sulfur.dioxide              density                   pH 
##                    0                    0                    0 
##            sulphates              alcohol              quality 
##                    0                    0                    0</code></pre>
<pre class="r"><code># data frequency for each column
sapply(wine_quality, n_distinct)</code></pre>
<pre><code>##        fixed.acidity     volatile.acidity          citric.acid 
##                   96                  143                   80 
##       residual.sugar            chlorides  free.sulfur.dioxide 
##                   91                  153                   60 
## total.sulfur.dioxide              density                   pH 
##                  144                  436                   89 
##            sulphates              alcohol              quality 
##                   96                   65                    6</code></pre>
<p><br></p>
<hr />
</div>
</div>
<div id="question-3---data-analysis" class="section level2">
<h2>Question 3 - Data Analysis</h2>
<p><br></p>
<div id="q3.-a" class="section level3">
<h3>Q3. A</h3>
<blockquote>
<p>To begin optimizing the fermentation process, we need to aggregate
all variable levels by quality rating to eliminate results that show no
clear correlation with quality.</p>
</blockquote>
<pre class="r"><code># aggregate all variables by quality
aggregate(. ~ quality, data = wine_quality, FUN = mean)</code></pre>
<pre><code>##   quality fixed.acidity volatile.acidity citric.acid residual.sugar  chlorides
## 1       3      8.360000        0.8845000   0.1710000       2.635000 0.12250000
## 2       4      7.779245        0.6939623   0.1741509       2.694340 0.09067925
## 3       5      8.167254        0.5770411   0.2436858       2.528855 0.09273568
## 4       6      8.347179        0.4974843   0.2738245       2.477194 0.08495611
## 5       7      8.872362        0.4039196   0.3751759       2.720603 0.07658794
## 6       8      8.566667        0.4233333   0.3911111       2.577778 0.06844444
##   free.sulfur.dioxide total.sulfur.dioxide   density       pH sulphates
## 1            11.00000             24.90000 0.9974640 3.398000 0.5700000
## 2            12.26415             36.24528 0.9965425 3.381509 0.5964151
## 3            16.98385             56.51395 0.9971036 3.304949 0.6209692
## 4            15.71160             40.86991 0.9966151 3.318072 0.6753292
## 5            14.04523             35.02010 0.9961043 3.290754 0.7412563
## 6            13.27778             33.44444 0.9952122 3.267222 0.7677778
##     alcohol
## 1  9.955000
## 2 10.265094
## 3  9.899706
## 4 10.629519
## 5 11.465913
## 6 12.094444</code></pre>
<blockquote>
<p>A quick check of the standard deviation‑to‑mean relationship reveals
that only citric acid shows a consistency issue as wine quality
decreases.</p>
</blockquote>
<pre class="r"><code># create a data frame of standard deviation / mean
deviation &lt;- c(
  volatile_acidity = mean(aggregate(volatile.acidity ~ quality, data = wine_quality, FUN = function(x) sd(x)/mean(x))[[2]]),
  citric_acid = mean(aggregate(citric.acid ~ quality, data = wine_quality, FUN = function(x) sd(x)/mean(x))[[2]]),
  chlorides = mean(aggregate(chlorides ~ quality, data = wine_quality, FUN = function(x) sd(x)/mean(x))[[2]]),
  density = mean(aggregate(density ~ quality, data = wine_quality, FUN = function(x) sd(x)/mean(x))[[2]]),
  pH = mean(aggregate(pH ~ quality, data = wine_quality, FUN = function(x) sd(x)/mean(x))[[2]]),
  sulphates = mean(aggregate(sulphates ~ quality, data = wine_quality, FUN = function(x) sd(x)/mean(x))[[2]]),
   alcohol = mean(aggregate(alcohol ~ quality, data = wine_quality, FUN = function(x) sd(x)/mean(x))[[2]]))

# generate a table for presentation
tibble(
  Variable = tools::toTitleCase(gsub(&quot;_&quot;, &quot; &quot;, names(deviation))),
  Coefficient = paste0(round(deviation * 100, 1), &quot;%&quot;)) %&gt;%
  kable(align = c(&quot;l&quot;, &quot;r&quot;), col.names = c(&quot;**Variable**&quot;, &quot;**Deviation**&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"><strong>Variable</strong></th>
<th align="right"><strong>Deviation</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Volatile Acidity</td>
<td align="right">33.4%</td>
</tr>
<tr class="even">
<td align="left">Citric Acid</td>
<td align="right">85%</td>
</tr>
<tr class="odd">
<td align="left">Chlorides</td>
<td align="right">49.7%</td>
</tr>
<tr class="even">
<td align="left">Density</td>
<td align="right">0.2%</td>
</tr>
<tr class="odd">
<td align="left">pH</td>
<td align="right">4.9%</td>
</tr>
<tr class="even">
<td align="left">Sulphates</td>
<td align="right">24.3%</td>
</tr>
<tr class="odd">
<td align="left">Alcohol</td>
<td align="right">8.9%</td>
</tr>
</tbody>
</table>
<blockquote>
<p>We need to determine the top correlators by calculating a modified
correlation coefficient for the variables and eliminating any results
with less than 75% correlation.</p>
</blockquote>
<pre class="r"><code># tally high quality values.
volatileacidity &lt;- wine_quality[wine_quality$volatile.acidity &lt; 0.497, ]
citricacid &lt;- wine_quality[wine_quality$citric.acid &gt; 0.273, ]
chlorides &lt;- wine_quality[wine_quality$chlorides &lt; 0.0849, ]
density &lt;- wine_quality[wine_quality$density &gt; 0.996, ]
pH &lt;- wine_quality[wine_quality$pH &lt; 3.31, ]
sulphates &lt;- wine_quality[wine_quality$sulphates &gt; 0.675, ]
alcohol &lt;- wine_quality[wine_quality$alcohol &gt; 10.6, ]

# total high quality wines
high_quality_total &lt;- sum(wine_quality$quality &gt;= 7)

# create data frame
contributions &lt;- c(
  volatile_acidity = sum(volatileacidity$quality &gt;= 7) / high_quality_total,
  citric_acid = sum(citricacid$quality &gt;= 7) / high_quality_total,
  chlorides = sum(chlorides$quality &gt;= 7) / high_quality_total,
  density = sum(density$quality &gt;= 7) / high_quality_total,
  pH = sum(pH$quality &gt;= 7) / high_quality_total,
  sulphates = sum(sulphates$quality &gt;= 7) / high_quality_total,
  alcohol = sum(alcohol$quality &gt;= 7) / high_quality_total)

# generate table for presentation
tibble(Variable = tools::toTitleCase(gsub(&quot;_&quot;, &quot; &quot;, names(contributions))),
                                     Coefficient = paste0(round(contributions * 100, 1), &quot;%&quot;)) %&gt;%
       kable(align = c(&quot;l&quot;, &quot;r&quot;), col.names = c(&quot;**Variable**&quot;, &quot;**Coefficient**&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"><strong>Variable</strong></th>
<th align="right"><strong>Coefficient</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Volatile Acidity</td>
<td align="right">75.6%</td>
</tr>
<tr class="even">
<td align="left">Citric Acid</td>
<td align="right">78.3%</td>
</tr>
<tr class="odd">
<td align="left">Chlorides</td>
<td align="right">73.3%</td>
</tr>
<tr class="even">
<td align="left">Density</td>
<td align="right">47.5%</td>
</tr>
<tr class="odd">
<td align="left">pH</td>
<td align="right">56.7%</td>
</tr>
<tr class="even">
<td align="left">Sulphates</td>
<td align="right">70.5%</td>
</tr>
<tr class="odd">
<td align="left">Alcohol</td>
<td align="right">78.8%</td>
</tr>
</tbody>
</table>
<blockquote>
<p>We can then establish a three‑factor testing floor. 69.1% of
high‑quality wines (rated 7–8) exceed the parameters of 9.9% alcohol,
0.570 g/L sulphate, and 0.171 g/L citric acid. This provides a solid
recommendation to set a bottom line requiring all wines to test above
these metrics.</p>
</blockquote>
<pre class="r"><code># find data with these parameters
floor_profile &lt;- wine_quality[
  wine_quality$citric.acid &gt; 0.171 &amp;
  wine_quality$alcohol &gt; 9.9 &amp;
  wine_quality$sulphates &gt; 0.570, ]

# calculate
low_profile &lt;- sum(floor_profile$quality &gt;= 7)
percentage &lt;- round(low_profile / sum(wine_quality$quality &gt;= 7) * 100, 1)

#generate table
kable(paste0(percentage, &quot;%&quot;), col.names = c(&quot;Floor Percentile&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Floor Percentile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">69.1%</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Lastly, we can determine a three‑factor testing benchmark. 5.1% of
high‑quality wines (rated 7–8) fall below the parameters of 12.0%
alcohol, 0.767 g/L sulphate, and 0.391 g/L citric acid. This provides a
solid recommendation for benchmarks to meet and should be set as Noble
Wines by Latulippe’s goal.</p>
</blockquote>
<pre class="r"><code># find data with these parameters
ceiling_profile &lt;- wine_quality[
  wine_quality$citric.acid &gt; 0.391 &amp;
  wine_quality$alcohol &gt; 12.0 &amp;
  wine_quality$sulphates &gt; 0.767, ]

# calculate
high_profile &lt;- sum(ceiling_profile$quality &gt;= 7)
percentage &lt;- round(high_profile / sum(wine_quality$quality &gt;= 7) * 100, 1)

# generate table
kable(paste0(percentage, &quot;%&quot;), col.names = c(&quot;Benchmark Percentile&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Benchmark Percentile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">5.1%</td>
</tr>
</tbody>
</table>
<p><br></p>
</div>
<div id="q3.-b" class="section level3">
<h3>Q3. B</h3>
<pre class="r"><code># generate alcohol bar chart
ggplot(wine_quality, aes(x = factor(quality), y = alcohol, fill = factor(quality), alpha = 0.5)) +
  stat_summary(fun = mean, geom = &quot;bar&quot;) +
  stat_summary(fun = mean, geom = &quot;text&quot;,
               aes(label = round(after_stat(y), 2)),
               vjust = -0.5, size = 4) +
  labs(title = &quot;Higher Alcohol Content Is Better&quot;,
       x = &quot;Quality Rating&quot;, y = &quot;Mean Alcohol (%)&quot;) +
  scale_y_continuous(
    breaks = seq(9, 12.5, by = 0.5)
  ) +
  coord_cartesian(ylim = c(9, 12.5)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5, face = &quot;bold&quot;),
        legend.position = &quot;none&quot;)</code></pre>
<p><img src="project4_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<blockquote>
<p>The bar chart displays the mean alcohol content for each quality
rating. A positive relationship is evident: higher alcohol levels are
associated with higher wine quality. The rate of increase in quality
becomes more pronounced as alcohol content rises.</p>
</blockquote>
<pre class="r"><code># generate sulphate boxplot
ggplot(wine_quality, aes(x = factor(quality), y = sulphates, fill = factor(quality))) +
  geom_boxplot(alpha = 0.5, coef = 0, outlier.shape = NA, median.colour = &quot;red&quot;) +
  labs(title = &quot;Low Sulphates Worsens Flavour&quot;,
       subtitle = &quot;(with median marker)&quot;,
       x = &quot;Quality Rating&quot;, y = &quot;Sulphates (g/L)&quot;) +
  scale_y_continuous(
    breaks = seq(0.5, 2, by = 0.05)) +
  coord_cartesian(ylim = c(0.5, .85)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5, face = &quot;bold&quot;),
        plot.subtitle = element_text(hjust = 0.5, color = &quot;red&quot;, face = &quot;italic&quot;, size = 8),
        legend.position = &quot;none&quot;)</code></pre>
<p><img src="project4_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<blockquote>
<p>The boxplot displays the upper and lower quartiles and the median
sulphate levels for each wine quality rating. A positive relationship
between sulphates and wine quality is evident. Lower‑end sulphate levels
show a tighter distribution compared to higher‑end levels.</p>
</blockquote>
<pre class="r"><code># generate citric acid violin plot
ggplot(wine_quality, aes(x = factor(quality), y = citric.acid, fill = factor(quality))) +
  geom_violin(trim = TRUE, alpha = 0.5) +
  stat_summary(fun = median, geom = &quot;point&quot;, shape = 21, size = 3, fill = &quot;red&quot;) +
  stat_summary(fun = median, geom = &quot;line&quot;, aes(group = 1), color = &quot;red&quot;, linewidth = 1) +
  labs(title = &quot;Citric Acid Does Not Deviate In Good Wine&quot;,
       subtitle = &quot;(with median slope line)&quot;,
       x = &quot;Quality Rating&quot;, y = &quot;Citric Acid (g/L)&quot;) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5, face = &quot;bold&quot;),
        plot.subtitle = element_text(hjust = 0.5, color = &quot;red&quot;, face = &quot;italic&quot;, size = 8),
        legend.position = &quot;none&quot;)</code></pre>
<p><img src="project4_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<blockquote>
<p>The violin plot illustrates the distribution of citric acid across
wine quality ratings. A positive relationship between citric acid levels
and quality ratings is evident. The data diverges further from the
median at lower citric acid levels, indicating greater variability.</p>
</blockquote>
<p><br></p>
</div>
<div id="q3.-c" class="section level3">
<h3>Q3. C</h3>
<blockquote>
<p>Higher alcohol percentage is strongly associated with increased wine
quality. The slope of the relationship rises from 0.31 to 0.63, showing
that quality improves more sharply as alcohol content increases. This
makes alcohol the decisive and principal variable in production
analysis.</p>
</blockquote>
<pre class="r"><code># calculate first and last slope
(10.27-9.96)/(4-3)</code></pre>
<pre><code>## [1] 0.31</code></pre>
<pre class="r"><code>(12.09-11.47)/(8-7)</code></pre>
<pre><code>## [1] 0.62</code></pre>
<blockquote>
<p>Sulphate levels rise with wine quality but plateau around 0.74 g/L,
as quality‑8 wines show no further increase. This ceiling effect
suggests limited benefit at higher concentrations and highlights that,
while sulphates generally exhibit a positive relationship with wine
quality, the highest concentrations reveal a negative association, as
seen when looking at maximum values. Excessive sulphate becomes
detrimental, limiting the overall upward trend. This pattern suggests,
costs associated with sulphates can be reduced by lowering the target
benchmark without risk of compromising product quality.</p>
</blockquote>
<pre class="r"><code># find max data in each quality score for sulphate
aggregate(sulphates ~ quality, data = wine_quality, FUN = max)</code></pre>
<pre><code>##   quality sulphates
## 1       3      0.86
## 2       4      2.00
## 3       5      1.98
## 4       6      1.95
## 5       7      1.36
## 6       8      1.10</code></pre>
<blockquote>
<p>The violin plot, supported by a standard deviation check, shows that
citric acid deviates further from the mean as wine quality decreases.
However, citric acid should remain a secondary concern compared to
alcohol content, since its levels exhibit overlapping ranges despite the
overall positive relationship with quality.</p>
</blockquote>
<pre class="r"><code># trend of deviation for citric acid
aggregate(citric.acid ~ quality, data = wine_quality, FUN = function(x) sd(x) / mean(x))</code></pre>
<pre><code>##   quality citric.acid
## 1       3   1.4658688
## 2       4   1.1543455
## 3       5   0.7386671
## 4       6   0.7125311
## 5       7   0.5182428
## 6       8   0.5101506</code></pre>
<p><br></p>
<hr />
</div>
</div>
<div id="question-4---strategic-recommendations" class="section level2">
<h2>Question 4 - Strategic Recommendations</h2>
<p><br></p>
<div id="q4.-a" class="section level3">
<h3>Q4. A</h3>
<blockquote>
<h3 id="recommendations-for-noble-wines-by-latulippe">Recommendations
for Noble Wines by Latulippe</h3>
<p><strong>Target alcohol levels of 12% or higher</strong><br />
Premium wines consistently show elevated alcohol content, achieved
through higher‑quality grapes and extended fermentation. Sugar
concentration itself does not drive quality, but grape quality ensures
optimal conditions to yield alcohol.</p>
<p><strong>Maintain citric acid consistency</strong><br />
High‑quality wines cluster tightly around 0.35–0.45 g/L citric acid.
Deviations outside this range reduce taste and predictability. Strict
monitoring of acid levels during fermentation is essential to preserve
consistency and consumer confidence.</p>
<p><strong>Lower costs with sulphate regulation</strong><br />
While sulphates correlate positively with wine quality, the benefit
plateaus around 0.74 g/L. Reducing sulphates to levels typical of
less‑than‑perfect wines avoids excess input costs without compromising
product quality.</p>
</blockquote>
<p><br></p>
<hr />
<p><a href="projects.html">← Back to Projects</a> | <a
href="index.html">← Back to Home</a></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
